/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package videojuego.vista;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import videojuego.elementos.Genero;
import videojuego.elementos.Main;
import static videojuego.elementos.Main.videojuegos;
import videojuego.elementos.Plataforma;
import videojuego.elementos.videojuego;
import videojuego.herramientas.AccionArchivo;
import videojuego.lista.ListaGenero;
import videojuego.lista.ListaPlataforma;
import videojuego.lista.ListaVideoJuegos;

/**
 *
 * @author arace
 */
public class ViewRegistr extends javax.swing.JFrame {
    //private videojuego video;
    //private ListaVideoJuegos video;
     //private ListaGenero listag;
     private ListaGenero listag;
     private ListaPlataforma listap;
   
        
    /**
     * Creates new form ViewRegistr
     */
    public ViewRegistr() {
        initComponents();
        String cantidad=String.valueOf(Main.videojuegos.size());
         String cantig=String.valueOf(Main.listag.size());
         String cantip=String.valueOf(Main.listap.size());
         System.out.println(cantig);
         System.out.println(cantip);
        //cargarGeneros();
        agregar2(); 
        agregarp();
    }

   public void agregar2()
  {
      for (Genero genero : Main.listag) {
        String ge = genero.getNombre();
        clasificacion.addItem(String.valueOf(ge));
        System.out.println(Main.listag.size()); 
    }
   
  }
   

      public void agregarp()
  {
     for (Plataforma plataforma : Main.listap) {
        String pl = plataforma.getNombre();
        plataform.addItem(String.valueOf(pl));
        System.out.println(Main.listap.size()); 
    }
          
    }
   
  
  
    
    public void agregar()
  {
      
      for (videojuego videoju : Main.videojuegos ) {
          Genero gen = videoju.getGenero();
        clasificacion.addItem(String.valueOf(gen));
    }
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formato = new javax.swing.ButtonGroup();
        multi = new javax.swing.ButtonGroup();
        descuento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nombre = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        desarrolladora = new javax.swing.JTextField();
        lanzamiento = new javax.swing.JTextField();
        Formato = new javax.swing.JPanel();
        Digital = new javax.swing.JRadioButton();
        Fisico = new javax.swing.JRadioButton();
        Multijugador = new javax.swing.JPanel();
        MultiSI = new javax.swing.JRadioButton();
        MultiNO = new javax.swing.JRadioButton();
        Descuento = new javax.swing.JPanel();
        DesSI = new javax.swing.JRadioButton();
        DesNO = new javax.swing.JRadioButton();
        CantDescuento = new javax.swing.JTextField();
        Limite = new javax.swing.JTextField();
        registrar = new javax.swing.JButton();
        clasificacion = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        plataform = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 720, 70));

        nombre.setBorder(javax.swing.BorderFactory.createTitledBorder("nombre"));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 130, 40));

        precio.setBorder(javax.swing.BorderFactory.createTitledBorder("precio"));
        jPanel1.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 180, -1));

        desarrolladora.setBorder(javax.swing.BorderFactory.createTitledBorder("Desarrolladora"));
        jPanel1.add(desarrolladora, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 160, -1));

        lanzamiento.setBorder(javax.swing.BorderFactory.createTitledBorder("lanzamiento"));
        jPanel1.add(lanzamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 130, -1));

        Formato.setBackground(new java.awt.Color(255, 255, 255));
        Formato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        Formato.setForeground(new java.awt.Color(51, 51, 51));

        formato.add(Digital);
        Digital.setForeground(new java.awt.Color(51, 51, 51));
        Digital.setText("Digital");

        formato.add(Fisico);
        Fisico.setForeground(new java.awt.Color(51, 51, 51));
        Fisico.setText("Fisico");

        javax.swing.GroupLayout FormatoLayout = new javax.swing.GroupLayout(Formato);
        Formato.setLayout(FormatoLayout);
        FormatoLayout.setHorizontalGroup(
            FormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Digital)
                .addGap(18, 18, 18)
                .addComponent(Fisico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FormatoLayout.setVerticalGroup(
            FormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormatoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Digital, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fisico, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(Formato, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        Multijugador.setBackground(new java.awt.Color(255, 255, 255));
        Multijugador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Multijugador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        Multijugador.setForeground(new java.awt.Color(51, 51, 51));

        MultiSI.setBackground(new java.awt.Color(255, 255, 255));
        multi.add(MultiSI);
        MultiSI.setForeground(new java.awt.Color(51, 51, 51));
        MultiSI.setText("Si");

        MultiNO.setBackground(new java.awt.Color(255, 255, 255));
        multi.add(MultiNO);
        MultiNO.setForeground(new java.awt.Color(51, 51, 51));
        MultiNO.setText("No");

        javax.swing.GroupLayout MultijugadorLayout = new javax.swing.GroupLayout(Multijugador);
        Multijugador.setLayout(MultijugadorLayout);
        MultijugadorLayout.setHorizontalGroup(
            MultijugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultijugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MultiSI)
                .addGap(18, 18, 18)
                .addComponent(MultiNO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MultijugadorLayout.setVerticalGroup(
            MultijugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultijugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MultijugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MultiSI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MultiNO, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Multijugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        Descuento.setBackground(new java.awt.Color(255, 255, 255));
        Descuento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descuento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        Descuento.setForeground(new java.awt.Color(51, 51, 51));

        descuento.add(DesSI);
        DesSI.setForeground(new java.awt.Color(51, 51, 51));
        DesSI.setText("Si");

        descuento.add(DesNO);
        DesNO.setForeground(new java.awt.Color(51, 51, 51));
        DesNO.setText("No");

        javax.swing.GroupLayout DescuentoLayout = new javax.swing.GroupLayout(Descuento);
        Descuento.setLayout(DescuentoLayout);
        DescuentoLayout.setHorizontalGroup(
            DescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescuentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DesSI)
                .addGap(18, 18, 18)
                .addComponent(DesNO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DescuentoLayout.setVerticalGroup(
            DescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescuentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DesSI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DesNO, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        CantDescuento.setForeground(new java.awt.Color(51, 51, 51));
        CantDescuento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Porcentaje de descuento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.add(CantDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 200, 56));

        Limite.setForeground(new java.awt.Color(51, 51, 51));
        Limite.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Limite del descuento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.add(Limite, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 170, -1));

        registrar.setText("registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        jPanel1.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        jPanel1.add(clasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 172, 100, 40));

        jButton1.setText("genero");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        jPanel1.add(plataform, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
private void cargarGeneros() {
      for (videojuego videojuegos : Main.videojuegos) {
        Genero gen = videojuegos.getGenero();
        if (gen != null) {
            clasificacion.addItem(gen.toString()); // Agrega el nombre del género al JComboBox
            System.out.println("Género agregado: " + gen);
        } else {
            System.out.println("El género es null para el videojuego: " + videojuegos);
        }
    }
  
    }


      
    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:
        
        int id =Main.videojuegos.size();
        String nombre=this.nombre.getText();
        String precio=this.precio.getText();
        double valor = Double.parseDouble(precio);
        String desarrolladora=this.desarrolladora.getText();
        String lanzamiento=this.lanzamiento.getText();
        String clasificacion = this.clasificacion.getSelectedItem().toString();
        
         String formato =((this.Digital.isSelected()) ? "Digital"  :"Fisico");
         boolean tieneDescuento=(this.DesSI.isSelected())?true:false;
         String cantidadDescuento=this.CantDescuento.getText();
         String limite=this.Limite.getText();
         boolean multiplaye=(this.MultiSI.isSelected())?true:false;
         Plataforma plataforma=null;
         Genero genero=null;
                  
         videojuego videoju = new videojuego(nombre, valor, desarrolladora, lanzamiento, clasificacion, limite, multiplaye);
// Crear objeto videojuego


// Agregar el videojuego a la lista de videojuegos
Main.videojuegos.add(videoju);

// Instanciar AccionArchivo con la ruta del archivo CSV
AccionArchivo archivo = new AccionArchivo("C:\\Users\\arace\\OneDrive\\Escritorio\\prueba.csv");

try {
    // Escribir el objeto videojuego en el archivo CSV
    archivo.llenarArchivo(videoju.toStringCSV());

    System.out.println("Datos guardados correctamente en el archivo CSV");

} catch (IOException ioe) {
    System.out.println("Error al escribir en el archivo CSV: " + ioe.getMessage());
    ioe.printStackTrace();
}

         // Se hace la prueba del arreglo de información
        try {
            // Se genera el proceso de lectura del archivo
            ArrayList<String> datosArchivo = archivo.leerArchivo();
            // Se itera y recorre la información
            for (String linea : datosArchivo) {
                System.out.println(linea);
            }
        } catch (IOException ioe) {
            System.out.println("Error al leer el archivo");
            ioe.printStackTrace();
        }
      
    }//GEN-LAST:event_registrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          Viewdos d= new Viewdos();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRegistr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRegistr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRegistr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRegistr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRegistr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantDescuento;
    private javax.swing.JRadioButton DesNO;
    private javax.swing.JRadioButton DesSI;
    private javax.swing.JPanel Descuento;
    private javax.swing.JRadioButton Digital;
    private javax.swing.JRadioButton Fisico;
    private javax.swing.JPanel Formato;
    private javax.swing.JTextField Limite;
    private javax.swing.JRadioButton MultiNO;
    private javax.swing.JRadioButton MultiSI;
    private javax.swing.JPanel Multijugador;
    private javax.swing.JComboBox<String> clasificacion;
    private javax.swing.JTextField desarrolladora;
    private javax.swing.ButtonGroup descuento;
    private javax.swing.ButtonGroup formato;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lanzamiento;
    private javax.swing.ButtonGroup multi;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> plataform;
    private javax.swing.JTextField precio;
    private javax.swing.JButton registrar;
    // End of variables declaration//GEN-END:variables

    void onGeneroAdded(String genero) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

  
}
